### PR TITLE
csl fix

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Comment by mirh** [comment]
You should future proof this slightly more, or the latest pandoc version isn't happy
(it complains "\vadjust cannot be used in vertical mode") https://github.com/jgm/pandoc/commit/356795dba06e2f1c4a0336c9836c132e97929926

**Comment by ismayc** [comment]
What do you suggest?

**Comment by mirh** [comment]
From the linked commit, fix number of parameters on CSLReferences, or pandoc 2.12 won't like it.

**Comment by ismayc** [comment]
Agreed, but what if someone doesn't have pandoc 2.12? How do you suggest future proofing for those that haven't updated as well?

**Comment by mirh** [comment]
Pandoc had already switched to it in 2.11.2, and even 2.11 seems to work just fine with `[2]`.

**Comment by ismayc** [comment]
Alright, we'll try it out! https://github.com/ismayc/thesisdown/pull/137

**Pull request merged**
