### PR TITLE
monashthesisdown

### PR DESCRIPTION
**Pull request by masiraji**
Hello!
Thank you for providing such a neat and reproducible way of writing theses. I have tried to add the Monash University template. Hope this helps

### CODE REVIEW

**Comment by ismayc** [comment]
Hi there! Could you just add a link in the README to your package instead of submitting a PR with all the files here? Thanks!

**Comment by ismayc** [comment]
Something similar to #158?

**Comment by masiraji** [comment]
Hello!
Thank you for the suggestions. I have added a link in the readme and submitted another PR. Sorry for the troouble.

**Comment by ismayc** [comment]
Not a problem!

**Pull request closed without merging**
