### PR TITLE
Update README file to account for error with tlmgr

### PR DESCRIPTION
**Pull request by AraujoH**
It'd be beneficial to add that users should run `tlmgr install babel-portuges` through the command prompt in case they're presented with the following error message.

```
tlmgr search --file --global "/brazil.ldf"
! Package babel Error: Unknown option `brazil'. Either you misspelled it
(babel)                or the language definition file brazil.ldf was not found
```

### CODE REVIEW

**Comment by ismayc** [comment]
Can you send this into `coppedown` instead of `thesisdown`?

**Comment by ismayc** [comment]
I'm going to add a line to the README, but close this PR since I think it should go into `coppedown` instead.

**Comment by AraujoH** [comment]
Hi, Chester

You're right. Thank you for doing this. As you can see, I'm not a
well-versed GitHub user and I misplaced the PR.

Best,
Hugo Araújo

**Comment by ismayc** [comment]
No problem! You'll get better with time :). Thanks for bringing this to my attention.

**Comment by AraujoH** [comment]
Thanks for the encouragement. It's much appreciated. =)

Take care,
Hugo Araújo

**Pull request closed without merging**
