### PR TITLE
Code protruding outside the left margin

### PR DESCRIPTION
**Pull request by nicksolomon**
1em was subtracted from the left margin in two different places, so code blocks had text hanging outside the shaded area. I deleted the second one.

### CODE REVIEW

**Comment by ismayc** [comment]
I wonder if these changes should really be suggested on the Reed LaTeX template too/instead?

**Comment by nicksolomon** [comment]
I'd be happy to submit a pull request there, but I can't seem to find a repo for it.

**Comment by ismayc** [comment]
I don't think there is one :(.  Ben Salzburg in CUS is the go to person though.  I think it is a good idea to suggest creating a repo too.

**Comment by nicksolomon** [comment]
Sad 😿 I'll shoot of an email to him suggesting github and my changes

**Pull request merged**
