### PR TITLE
Add ability to add extra pandoc arguments

### PR DESCRIPTION
**Pull request by shirdekel**
Fixes https://github.com/ismayc/thesisdown/issues/139

### CODE REVIEW

**Comment by ismayc** [comment]
Thanks, @shirdekel! This is very slick. I'd be happy to add you as a contributor to the {thesisdown} package if you'd like?

**Comment by shirdekel** [comment]
You're welcome! Thanks for the package :) Yes, I'd be happy to be added.

**Comment by ismayc** [comment]
You're welcome! Can you let me know your first and last name/given and surname and email address so I can add you as a contributor?

**Comment by shirdekel** [comment]
Shir Dekel shirdekel@yahoo.com.au

**Pull request merged**
