### PR TITLE
add option to change line spacing

### PR DESCRIPTION
**Pull request by simonpcouch**
Hey there!

The [senior handbook](https://www.reed.edu/registrar/pdfs/senior-handbook.pdf) currently advises that “Double-spaced and space-and-a-half are preferred” (p. 18). This PR adjusts the `index.Rmd` YAML to default to space-and-a-half and notes how to use single or double spacing instead. A less “breaking” change here could be continue defaulting to single-spaced but noting how to change spacing with similar code (a la 0ef60ec).

Not sure if `inst/markdown` is maintained anymore, but glad to drop these updates there if appreciated.

kbott and I checked in with library folks here to make sure we’re not introducing a change we ought not to. 

Thank you for your work on maintaining this package. :-)

### CODE REVIEW

**Comment by ismayc** [comment]
I'm keeping `inst` around though I prefer people to use the RStudio project flow so `inst` will probably be deprecated at some point when most academic years aren't in session (likely over the summer). If you switch over that, I'm happy to merge into `develop` and then into `master`.

**Comment by ismayc** [comment]
Thanks for letting me know about this change too!

**Comment by simonpcouch** [comment]
You got it! Just made those changes and redirected the PR.

**Comment by ismayc** [comment]
Thanks, @simonpcouch!

**Pull request merged**
